# Generated by Django 5.1.4 on 2025-07-04 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.CreateModel(
            name='PointsAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Puntos sumados o restados (puede ser negativo)')),
                ('reason', models.CharField(help_text='Motivo del ajuste (ej: Observación, Sanción, etc.)', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_adjustments', to='tournament.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_adjustments', to='tournament.team')),
            ],
        ),
    ]
