# Generated by Django 5.1.4 on 2026-01-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_matchday_match_match_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchday',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
