# Generated by Django 5.1.4 on 2026-05-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('seniors', 'Seniors'), ('super_seniors', 'Super Seniors')], default='seniors', max_length=20, verbose_name='Championship Category')),
                ('date', models.DateField(verbose_name='Match Day Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Match Day',
                'verbose_name_plural': 'Match Days',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('category', 'date'), name='unique_matchday_date_per_category')],
            },
        ),
    ]
