# Generated by Django 5.1.4 on 2026-05-21 15:07

from django.db import migrations, models
from django.utils.text import slugify


def populate_matchday_slugs(apps, schema_editor):
    MatchDay = apps.get_model('tournaments', 'MatchDay')
    for matchday in MatchDay.objects.all().order_by('id'):
        if matchday.slug:
            continue

        base_text = matchday.description or f"jornada-{matchday.date.strftime('%d-%m-%Y')}"
        base_slug = slugify(base_text)[:160] or 'jornada'
        slug_candidate = base_slug
        counter = 2
        while MatchDay.objects.exclude(pk=matchday.pk).filter(slug=slug_candidate).exists():
            slug_candidate = f"{base_slug}-{counter}"[:180]
            counter += 1

        matchday.slug = slug_candidate
        matchday.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchday',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.RunPython(populate_matchday_slugs, migrations.RunPython.noop),
    ]
