# Generated by Django 5.1.4 on 2026-09-03 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0004_matchevent'),
        ('teams', '0009_alter_player_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('seniors', 'Seniors'), ('super_seniors', 'Super Seniors')], max_length=20, unique=True)),
                ('teams_classified', models.PositiveIntegerField(default=8)),
                ('playoffs_enabled', models.BooleanField(default=False)),
                ('third_place_match', models.BooleanField(default=True)),
                ('playoffs_home_and_away', models.BooleanField(default=False)),
                ('penalties_on_aggregate_tie', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de liga',
                'verbose_name_plural': 'Configuraciones de liga',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Playoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('seniors', 'Seniors'), ('super_seniors', 'Super Seniors')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playoffs', to='playoffs.leaguesettings')),
            ],
            options={
                'verbose_name': 'Edicion de playoffs',
                'verbose_name_plural': 'Ediciones de playoffs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayoffTie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('quarterfinal', 'Cuartos de final'), ('semifinal', 'Semifinal'), ('third_place', 'Tercer puesto'), ('final', 'Final')], max_length=20)),
                ('position', models.PositiveSmallIntegerField()),
                ('home_penalties', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_penalties', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decided_by_penalties', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='playoff_away_ties', to='teams.team')),
                ('first_leg', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='playoff_first_leg', to='matches.match')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='playoff_home_ties', to='teams.team')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_playoff_ties', to='teams.team')),
                ('playoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ties', to='playoffs.playoff')),
                ('second_leg', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='playoff_second_leg', to='matches.match')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_playoff_ties', to='teams.team')),
            ],
            options={
                'verbose_name': 'Llave de playoffs',
                'verbose_name_plural': 'Llaves de playoffs',
                'ordering': ['round', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='playoff',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('category',), name='one_active_playoff_per_category'),
        ),
        migrations.AddConstraint(
            model_name='playofftie',
            constraint=models.UniqueConstraint(fields=('playoff', 'round', 'position'), name='unique_playoff_tie_position'),
        ),
        migrations.AddConstraint(
            model_name='playofftie',
            constraint=models.CheckConstraint(condition=models.Q(('home_team__isnull', True), models.Q(('home_team', models.F('away_team')), _negated=True), _connector='OR'), name='playoff_tie_teams_are_different'),
        ),
    ]
