# Generated by Django 5.1.4 on 2026-09-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playoffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playofftie',
            name='round',
            field=models.CharField(choices=[('round_of_16', 'Octavos de final'), ('quarterfinal', 'Cuartos de final'), ('semifinal', 'Semifinal'), ('third_place', 'Tercer puesto'), ('final', 'Final')], max_length=20),
        ),
    ]
