# Generated by Django 5.1.4 on 2026-09-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playoffs', '0003_restart_playoff_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playoff',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cuadro de playoffs', 'verbose_name_plural': 'Cuadros de playoffs'},
        ),
        migrations.RenameIndex(
            model_name='playoffmatch',
            new_name='playoffs_pl_tie_id_b39313_idx',
            old_name='playoffs_pl_tie_id_leg_7f0df0_idx',
        ),
        migrations.AlterField(
            model_name='playofftie',
            name='next_slot',
            field=models.CharField(blank=True, choices=[('home', 'Local'), ('away', 'Visitante')], max_length=4),
        ),
    ]
