# Generated by Django 5.1.4 on 2026-05-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='key',
            field=models.CharField(choices=[('team_manager_enable_players', 'Permitir que Team Manager habilite jugadores'), ('team_manager_edit_team', 'Permitir que Team Manager edite equipo')], max_length=80, unique=True),
        ),
    ]
