# Generated by Django 5.1.4 on 2026-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appconfiguration_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='key',
            field=models.CharField(choices=[('team_manager_enable_players', 'Permitir que Team Manager habilite jugadores'), ('team_manager_edit_team', 'Permitir que Team Manager edite equipo'), ('enable_push_notifications', 'Habilitar notificaciones push')], max_length=80, unique=True),
        ),
    ]
