# Generated by Django 5.1.4 on 2026-08-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(default='Super Liga Nacional Florida', max_length=120)),
                ('primary_color', models.CharField(default='#cc0000', max_length=7)),
                ('secondary_color', models.CharField(default='#990000', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('hero_bg_img', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('footer_location_name', models.CharField(default='SANTA CRUZ DE LA SIERRA', max_length=160)),
                ('footer_organizer_name', models.CharField(default='PROMO 2001T', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branding de la liga',
                'verbose_name_plural': 'Branding de la liga',
            },
        ),
    ]
