# Generated by Django 5.1.4 on 2026-08-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitebranding_league_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='key',
            field=models.CharField(choices=[('team_manager_enable_players', 'Permitir que Team Manager habilite jugadores'), ('team_manager_edit_team', 'Permitir que Team Manager edite equipo'), ('enable_push_notifications', 'Habilitar notificaciones push'), ('player_field_graduation_year', 'Mostrar año de egreso en jugadores'), ('player_field_birth_date', 'Mostrar fecha de nacimiento en jugadores'), ('player_field_photo', 'Mostrar foto en jugadores'), ('player_field_sub35', "Mostrar campo 'Es Sub35' en jugadores")], max_length=80, unique=True),
        ),
    ]
