# Generated by Django 5.1.4 on 2026-07-11 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0004_matchevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Monto ($)')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment', to='matches.matchevent', verbose_name='Evento de tarjeta')),
            ],
            options={
                'verbose_name': 'Pago de tarjeta',
                'verbose_name_plural': 'Pagos de tarjetas',
                'ordering': ['match_event__team__name', '-match_event__created_at'],
            },
        ),
    ]
