# Generated by Django 5.1.4 on 2026-05-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ORGANIZER', 'Organizador'), ('TEAM_MANAGER', 'Encargado de Equipo'), ('REFEREE', 'Arbitro'), ('PLAYER', 'Jugador')], default='PLAYER', max_length=20, verbose_name='Role'),
        ),
    ]
