# Generated by Django 5.1.4 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="Nombre")),
                ("image", models.ImageField(upload_to="sponsors/", verbose_name="Imagen")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Auspiciador",
                "verbose_name_plural": "Auspiciadores",
                "ordering": ["name"],
            },
        ),
    ]
