# Generated by Django 5.1.4 on 2026-05-15 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Team Name')),
                ('coach', models.CharField(max_length=100, verbose_name='Coach Name')),
                ('category', models.CharField(choices=[('seniors', 'Seniors'), ('super_seniors', 'Super Seniors')], default='seniors', max_length=20, verbose_name='Championship Category')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Team Logo')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Player Name')),
                ('number', models.PositiveIntegerField(verbose_name='Jersey Number')),
                ('position', models.CharField(choices=[('GK', 'Arquero'), ('DF', 'Defensa'), ('MF', 'Mediocampista'), ('FW', 'Delantero')], max_length=2, verbose_name='Position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team', verbose_name='Team')),
            ],
        ),
    ]
