# Generated by Django 5.1.4 on 2026-05-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_is_available_for_matchday'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_reinforcement',
            field=models.BooleanField(default=False, verbose_name='Es refuerzo'),
        ),
    ]
