# Generated by Django 5.1.4 on 2026-05-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_player_is_reinforcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='goals_scored',
            field=models.PositiveIntegerField(default=0, verbose_name='Goles'),
        ),
    ]
