# Generated by Django 5.1.4 on 2026-05-21 15:07

from django.db import migrations, models
from django.utils.text import slugify


def populate_team_slugs(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    for team in Team.objects.all().order_by('id'):
        if team.slug:
            continue

        base_slug = slugify(team.name)[:140] or 'equipo'
        slug_candidate = base_slug
        counter = 2
        while Team.objects.exclude(pk=team.pk).filter(slug=slug_candidate).exists():
            slug_candidate = f"{base_slug}-{counter}"[:160]
            counter += 1

        team.slug = slug_candidate
        team.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_player_goals_scored'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.RunPython(populate_team_slugs, migrations.RunPython.noop),
    ]
