# Generated by Django 5.1.4 on 2026-08-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_sub35',
            field=models.BooleanField(default=False, verbose_name='Es Sub35'),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/', verbose_name='Foto'),
        ),
    ]
