# Generated by Django 5.1.4 on 2026-08-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_player_birth_date_player_is_sub35_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jersey Number'),
        ),
    ]
