# Generated by Django 5.1.4 on 2026-05-18 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_manager_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('SYSTEM', 'Sistema'), ('MATCH', 'Partidos'), ('TEAM', 'Equipos'), ('STANDINGS', 'Clasificaciones'), ('PAYMENT', 'Pagos'), ('REMINDER', 'Recordatorios')], default='SYSTEM', max_length=20)),
                ('audience_type', models.CharField(choices=[('ALL', 'Todos'), ('TEAM', 'Por equipo'), ('USER', 'Por usuario'), ('ROLE', 'Por rol')], default='ALL', max_length=10)),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('ORGANIZER', 'Organizador'), ('TEAM_MANAGER', 'Encargado de Equipo'), ('REFEREE', 'Arbitro'), ('PLAYER', 'Jugador')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_teams', models.ManyToManyField(blank=True, related_name='notifications', to='teams.team')),
                ('target_users', models.ManyToManyField(blank=True, related_name='target_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-delivered_at'],
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
