# Generated by Django 5.1.4 on 2026-05-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="court",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Cancha 1"), (2, "Cancha 2"), (3, "Cancha 3")],
                default=1,
                verbose_name="Cancha",
            ),
        ),
    ]
