# Generated by Django 5.1.4 on 2026-05-21 15:07

from django.db import migrations, models
from django.utils.text import slugify


def populate_match_slugs(apps, schema_editor):
    Match = apps.get_model('matches', 'Match')
    for match in Match.objects.select_related('home_team', 'away_team', 'match_day').all().order_by('id'):
        if match.slug:
            continue

        if match.match_day and match.match_day.description:
            matchday_ref = match.match_day.description
        elif match.match_day:
            matchday_ref = f"jornada-{match.match_day.date.strftime('%d-%m-%Y')}"
        else:
            matchday_ref = f"jornada-{match.date.strftime('%d-%m-%Y')}"

        base_text = f"{match.home_team.name}-vs-{match.away_team.name}-{matchday_ref}"
        base_slug = slugify(base_text)[:200] or 'partido'
        slug_candidate = base_slug
        counter = 2
        while Match.objects.exclude(pk=match.pk).filter(slug=slug_candidate).exists():
            slug_candidate = f"{base_slug}-{counter}"[:220]
            counter += 1

        match.slug = slug_candidate
        match.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.RunPython(populate_match_slugs, migrations.RunPython.noop),
    ]
